services:
  mongodb:
    image: mongo:latest
    build: docker/mongo
    container_name: sequra-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./docker/volumes/mongo:/data/db
      - ./docker/volumes/mongo_config:/data/configdb
    networks:
      - sequra-network

volumes:
  mongodb_data:

networks:
  sequra-network:
    driver: bridge 